name: Push to S3
on: push
jobs:
  push_to_s3:
    runs-on: amazon/aws-cli
    steps:
      - name: "Push to S3"
        run: aws s3 ls
        env:
          LOCAL_FILE: dist/index.html
          REMOTE_FILE: index.html
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}